### ISSUE TITLE
Northern orientation due to click on arrow

### ISSUE THREAD

**Issue by aka-hades** [Akaflieg-Freiburg/enroute#25] opened 2020-02-19 20:06 UTC
Rotating the direction of the map can only be changed by rotating by two fingers. It's hard to find a Northern oriented direction again.

Proposed solutionb
Clicking on the compass card orients the map Northern

**Comment by kebekus** [comment] 2020-02-20 06:50
Duplicate of #16

**Comment by kebekus** [comment] 2020-02-20 06:50
Will be addressed in a future release.

**Closed by kebekus** 2020-02-20 06:50 UTC
