### ISSUE TITLE
EditText is not displaying when user try to edit flight route data

### ISSUE THREAD

**Issue by SKocur** [Akaflieg-Freiburg/enroute#48] opened 2020-06-25 10:49 UTC
Hello, I have an issue with Android Enroute app installed on Samsung Galaxy A8 (EditText is not displaying when user wants to edit route data). It works on Samsung Galaxy S7.

Steps to reproduce (on Samsung Galaxy A8):
* clean install app
* open navigation drawer menu
* click "Route"
* swipe to "Aircraft and ..." tab
* try to edit anything

It does not work even if you specify waypoints.

**Comment by kebekus** [comment] 2020-06-26 05:10
Hello, this is bad. I do not have access to a Galaxy A8 device and have not been able to reproduce the issue. Would you be able to produce a little screencast video of the failure, so I can see how exactly the issue looks like?

**Comment by SKocur** [comment] 2020-06-26 06:04
Yes, sure, here you are

**Comment by SKocur** [comment] 2020-06-26 06:11
![received_860654424428548](https://user-images.githubusercontent.com/19364933/85826254-84373c80-b784-11ea-9252-78a237853054.gif)

**Comment by kebekus** [comment] 2020-06-26 06:14
I understand! The display is so narrow that the text fields have size zero! Can you quickly check if it help to turn the device sideways, so that there is more horizontal screen space?

**Comment by SKocur** [comment] 2020-06-26 13:48
Sorry for late respose. You are right, this field is displayed correctly if you use app in horizontal orientation.

**Comment by kebekus** [comment] 2020-06-26 14:17
Very well. I will try to have a bugfix in place for the next release. Thank you for reporting this.

**Comment by SKocur** [comment] 2020-06-26 15:46
Thank you for doing great job! Keep it up :)

**Comment by kebekus** [comment] 2020-07-07 06:19
Dear SKocur,

a little unrelated to your bug report … you seem very competent with computers. Are you interested in maintaining a Polish translation of our app? Also, we are constantly looking out for competent contributors…

Best,

Stefan

**Comment by kebekus** [comment] 2020-07-07 06:20
Bug has been fixed. Bugfix will be included in version 1.8.0, scheduled to appear in a month or so.

**Closed by kebekus** 2020-07-07 06:20 UTC
Labels: bug

**Comment by SKocur** [comment] 2020-07-07 09:25
Hello Stefan, I would like to become contributor. We can talk via e-mail: skocur10{at}gmail[dot]com

Glad that you fixed it! :)
