### ISSUE TITLE
Custom raster mbtile not showing since updated

### ISSUE THREAD

**Issue by gabouls8** [Akaflieg-Freiburg/enroute#384] opened 2024-03-01 00:33 UTC
**Describe the bug**
Enroute v2.30.02 was working well with raster mbtile on Android (Redmi note 8pro). Since last update I can't see my custom map. Just a grey screen with the notam roadsigns icon. I found v2.30.02 back on apkcombo, and got my map again on the screen..

**To Reproduce**
Probably not related with my map, but there it is:
https://drive.google.com/file/d/1WFJdjMdBmNa_S0cp69bZGmKyYP7G3F8h/view?usp=share_link

 
**Smartphone (please complete the following information):**
 - Device: Redmi note 8 pro
 - OS: android 10
 - Browser brave
 - Version 

**Additional context**
Just curious why airspace overlay is not possible with custom raster mbtile, as a side question..

**Comment by kebekus** [comment] 2024-03-01 06:39
@gabouls8 Dear Gabriel, thank you for your report. I can reproduce the issue on my machine and will start to investigate…

**Comment by kebekus** [comment] 2024-03-01 13:54
@gabouls8 Dear Gabriel, I have (hopefully) fixed the issue. A new version of Enroute Flight Navigation (=2.30.8) is available to beta testers at Google Play. Can you please try that version and confirm that the problem is solved?

Feel free to return to me if you have difficulties registering as a beta tester.

Best wishes from Freiburg,

Stefan.

**Comment by gabouls8** [comment] 2024-03-01 13:58
Yep, it works perfect 😎🙏

**Comment by kebekus** [comment] 2024-03-01 16:53
@gabouls8 Thanks again for the report -- there are some issues that we would find with help from our user community. I uploaded 2.30.8 just now; the release should become public shortly.

Please feel free to report more bugs in the future. We hope that you won't find any.

**Comment by kebekus** [comment] 2024-03-01 16:54
@gabouls8 The sample map that you sent looked seriously interesting. We do plan to fly the glider in the Alps this summer, and I wonder if there is a public source for the data.

**Comment by kebekus** [comment] 2024-03-01 16:54
Closing because fixed in 2.30.8.

**Closed by kebekus** 2024-03-01 16:54 UTC
Labels: bug

**Comment by gabouls8** [comment] 2024-03-01 18:34
Glad you asked. It was just published there:
https://drive.google.com/drive/folders/1fr68iDfBMsFurlEx9bBe8ZorvOEG9Lc7?usp=sharing
My mail adress in the readme there.
The discussion on the french gliding forum:
https://www.volavoile.net/topic/14449-fond-de-carte-custom-pour-les-alpes/

So far it is just two of us, Frank doing the calculation to generate the vector layer with all the sectors, circles, and soon a filter to get the location of all the useful mountain passes, and me how tried to make it all look good on a map.

We would love if somehow there could be something we could do together. Like switching that layer on or off in enroute, having several layers installed and being able to change which layer displays (I couldn't do that so far, I had to uninstall one to see the next one)

In the meantime I'm quite happy about my city and peaks selection for the map, I'm happy to tell you anything I've done if you think it could be of use for you. By the way on the french forum there is a link to a GitHub repo with a still short but maintained list of peaks and passes..

**Comment by kebekus** [comment] 2024-03-05 19:40
@gabouls8 Dear Gabriel, thanks for the explanation. I am seriously impressed by your maps and I'd be more than glad to cooperate with you. I am however currently on a business trip, with very limited time. Please give me two weeks or so before I can come back to you.

**Comment by kebekus** [comment] 2024-03-13 06:16
@gabouls8 Dear Gabriel, the feature that you request is reasonable and useful, so we added it to our TODO-List. I have opened a feature request here:

- https://github.com/Akaflieg-Freiburg/enroute/issues/390

Could you please go to that page and subscribe to it? That will simplify our communication and keep you informed of any progress. 

Fine print: We have very limited manpower for development, so let me ask for your understanding if the feature is not implemented as quickly as you would like. Any help is greatly welcome!

Best,

Stefan.

**Comment by kebekus** [comment] 2024-11-22 05:48
@gabouls8 Dear Gabriel, earlier this year we had a conversation about the user interface for raster maps in the Enroute Flight Navigation software. I have implemented your suggestion: raster maps can now conveniently be switched on and off during the flight. The feature is found in version 2.32.1, which is available on Google Play. An iOS version will likely come out in a few weeks.

Thanks again for your comments and suggestions.

**Comment by kebekus** [comment] 2024-11-22 05:50
@gabouls8 Another thing: Enroute draws raster maps above the standard maps, which show aviation data. If you make your map a little transparent, then users can see the aviation map AND your data on top. Please be in touch if I can be of any help!

**Comment by gabouls8** [comment] 2025-01-09 22:06
@kebekus hi stephan, sorry i just saw this. I remember seeing your comment on march 13, but later i didn't know how to get back to your message 😞 

Great news !!!
I look at it and add the mention on the readme of the new project page:
https://github.com/gabouls8/MountainCircles/blob/main/README.md

Now the whole algorithm is open source 🥳

**Comment by gabouls8** [comment] 2025-01-09 22:45
ok, so i tried  with raster mbtiles that i exported in png format, where i have only the circles and altitudes written. The font is too big basically. I would need to redo it in QGIS, and figure out which font size work..

Now all the data is in vector form as well. (you can find some vector data here in geojson https://drive.google.com/file/d/1bVcR0HGvBMT2LIqNdTZlI4UlNaQMgH60/view?usp=sharing)

if i convert it in vector mbtiles, and add it to enroute, enroute will try to render it as an airspace, won't it? like class D, CTR, TMA and so on?
How hard would it be for you to add a style for "mountain circles" alongside all the airspace styles? Like black, 2px, labels font 11px...

Because a raster mbtile 99% transparent as I mentioned above is 200Mb, whereas the vector one is 22Mb. This way whe can have a set of vector mbtiles ( like full alps in L/D 20 and 25, and the home base only that extends way further ) and switch on demand, if you see what i mean.

gabriel.briffe@gmail.com
