### ISSUE TITLE
Aerodrome not visible at certain zoom levels

### ISSUE THREAD

**Issue by ubx** [Akaflieg-Freiburg/enroute#421] opened 2024-07-15 18:45 UTC
**Describe the bug**
Aerodrome not visible at certain zoom levels.

**To Reproduce**
1. Navigate to aerodrome LSTB (Bellechasse)
2. Zoom in to 6 km : aerodrome LSTB not visible
3. Zoom in to 3 km : aerodrome LSTB visible
4. Zoom out to 10 km: aerodrome LSTB visible

**Expected behavior**
The aerodrome should be visible at all zoom levels.

**Screenshots**
![Zoom 6 km](https://github.com/user-attachments/assets/38628541-eff0-4b45-9347-c83896258915)
![Zoom 3 km](https://github.com/user-attachments/assets/20b8d3b4-e687-4a56-bf06-acb5290559c4)
![Zoom 10 km](https://github.com/user-attachments/assets/74a8d504-1766-4ecc-8de1-fa5f1ed4884f)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S7
 - OS: Android
 - Version 8.0
 - App version: 2.31.04 -GIT #6b8b4719

**Comment by kebekus** [comment] 2024-07-16 06:20
@ubx Thank you for the report. I will look into the issue. Still, we would like your understanding that we will take substantial time. We are a small team and program the app in our spare time. Development is slow, and we must prioritize strictly.

**Comment by kebekus** [comment] 2024-10-06 07:16
@ubx Update: I will start to work on this issue now.

**Comment by kebekus** [comment] 2024-10-06 07:19
@schneisi Will backport MapLibre style from external JSON into QML, which should give a better fine-tuning about drawing priorities, and as an additional benefit allows to change map properties dynamically. We had something like that in Qt5, and needed to change that for Qt6. Now MapLibre has caught up and we can revert to the old version.

**Comment by kebekus** [comment] 2024-10-11 06:59
The issue is fixed in version 2.31.12, which has become available at Google Play and will hopefully become available for iOS devices in the next few days or so. I am closing this issue now

@ubx Dear Andreas, thanks again for your report. Please feel free to re-open this issue if you are not satisfied with the fix. Please keep reporting issues that you become aware of.

**Closed by kebekus** 2024-10-11 06:59 UTC
Labels: enhancement

**Comment by ubx** [comment] 2024-10-13 08:39
Perfect! Thanks for the fix.
