### ISSUE TITLE
Popup bug

### ISSUE THREAD

**Issue by 2dylan1** [Akaflieg-Freiburg/enroute#382] opened 2024-02-26 12:53 UTC
If i remove a checkpoint on the Route and wind window, the pop up stays there

1. Go to route and wind
2. Click on a waypoint to remove the waypoint 
3. Scroll down to remove 

Im on Android 
Xiaomi Redmi note 11 pro 

App version v2.30.5

![Screenshot_2024-02-26-14-44-41-619_de akaflieg_freiburg enroute](https://github.com/Akaflieg-Freiburg/enroute/assets/119488451/7c71d1b2-78d6-4d69-89e6-c8cc7948a59f)

**Comment by kebekus** [comment] 2024-02-26 19:33
@2dylan1 Thank you for the report. I can reproduce the issue here and will try to come up with a fix ASAP.

Best,

Stefan.

**Comment by kebekus** [comment] 2024-02-27 07:58
@2dylan1 The issue is (hopefully) fixed in 2.30.7, which is now available for beta testing at Google Play. Can you please try the new version and let me know if the problem is resolved for you? -- Thanks!

**Closed** 2024-03-01 16:56 UTC
Labels: bug
